version: "3"
services:
  mageai:
    image: mageai/mageai:latest
    command: ["mage", "start", "${PROJECT_NAME}"]
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
      - ./.dlt:/home/src/${PROJECT_NAME}/.dlt
    restart:
      on-failure:5

      # - ./.dlt:/home/src/.dlt
      # - ./${PROJECT_NAME}:/home/src/${PROJECT_NAME}
