version: "3"
services:
  mageai:
    image: mageai/mageai:alpha
    command: ["mage", "start", "${PROJECT_NAME}"]
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5
