version: "3"
services:
  mageai:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["mage", "run", "${PROJECT_NAME}", "load_rawg_bq_bar_chart_m2"]
    env_file:
      - .env
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
      - ./.dlt:/home/src/${PROJECT_NAME}/.dlt
    restart:
      on-failure:5

      # - ./.dlt:/home/src/.dlt
      # - ./${PROJECT_NAME}:/home/src/${PROJECT_NAME}
