project_type: standalone

variables_dir: ~/.mage_data
# remote_variables_dir: s3://bucket/path_prefix

variables_retention_period: '90d'

emr_config:
spark_config:
  # Application name
  app_name: my spark app
  spark_master: local
  executor_env: {}
  spark_jars: []
  spark_home:
  others: {}
  use_custom_session: false
  custom_session_var_name: spark
notification_config:
  alert_on:
  - trigger_failure
  - trigger_passed_sla
  slack_config:
    webhook_url: "{{ env_var('MAGE_SLACK_WEBHOOK_URL') }}"
  teams_config:
    webhook_url: "{{ env_var('MAGE_TEAMS_WEBHOOK_URL') }}"
project_uuid: 3203dbf3bb7d411a87c6f9b37e8d09d4
help_improve_mage: true
features:
  display_local_timezone: true
  command_center: true
  add_new_block_v2: false
  code_block_v2: true
  dbt_v2: true
  compute_management: true
pipelines:
remote_variables_dir:
