
[destination.bigquery]
location = "US"

[destination.bigquery.credentials]
project_id= 
private_key= 

[destination.postgres.credentials]
database = "rawg"
username = "postgres"
password = "postgres" 
host = "db-postgres"
port = 5432
connect_timeout = 15