[destination.bigquery]
location = "US"

[destination.bigquery.credentials]
project_id= "de-tf-411908"
private_key_id= "4f5f7dc2712bde917b8deefe931804f6feec7513"
client_email= "mage-gcp-orchestraction@de-tf-411908.iam.gserviceaccount.com"